# Generated by Django 3.2.16 on 2022-11-29 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='login',
            name='fname',
            field=models.CharField(default='null', max_length=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='login',
            name='lname',
            field=models.CharField(default='null', max_length=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='login',
            name='mname',
            field=models.CharField(default='null', max_length=12),
            preserve_default=False,
        ),
    ]
