# Generated by Django 3.2.16 on 2022-11-29 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20221129_1444'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='login',
            name='cpassword',
        ),
    ]
