# Generated by Django 3.2.16 on 2022-12-05 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_remove_login_cpassword'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tlogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=122)),
                ('title', models.CharField(max_length=195)),
                ('date', models.DateField()),
            ],
        ),
    ]
