# Generated by Django 3.2.16 on 2022-12-05 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_tlogs'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tlog_body',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tlog_id', models.IntegerField()),
                ('body', models.TextField(blank=True, null=True)),
                ('image', models.TextField(blank=True, null=True)),
                ('email', models.CharField(blank=True, max_length=122, null=True)),
                ('title', models.CharField(blank=True, max_length=195, null=True)),
                ('date', models.DateField()),
            ],
        ),
    ]
