# Generated by Django 3.2.16 on 2022-12-16 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_tlog_body_tlog_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tlog_body',
            old_name='tlog_id',
            new_name='tlog',
        ),
    ]
