# Generated by Django 3.2.16 on 2022-12-16 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_alter_tlogs_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tlogs',
            name='email',
            field=models.CharField(max_length=122),
        ),
    ]
