# Generated by Django 3.2.16 on 2022-12-16 08:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0011_alter_tlogs_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='Tlogs',
            old_name='email',
            new_name='email_id',
        ),
    ]
