# Generated by Django 3.2.16 on 2022-12-16 08:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0012_alter_tlogs_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tlogs',
            name='email_id',
        ),
        migrations.AddField(
            model_name='tlogs',
            name='email',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
            preserve_default=False,
        ),
    ]
