# Generated by Django 3.2.16 on 2022-12-16 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_alter_tlogs_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='Tlogs',
            old_name='email',
            new_name='email_id',
        ),
    ]
