# Generated by Django 3.2.16 on 2022-12-17 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_alter_tlogs_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tlogs',
            name='email_id',
        ),
        migrations.AddField(
            model_name='tlogs',
            name='email',
            field=models.CharField(default='harshpratap652@gmail.com', max_length=122),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tlogs',
            name='publish',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
