# Generated by Django 3.2.16 on 2022-12-20 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_tlogs_views'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tlogs',
            name='views',
            field=models.IntegerField(blank=True, default='0', null=True),
        ),
    ]
