# Generated by Django 3.2.16 on 2022-12-20 16:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_alter_tlogs_views'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tlog_comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(blank=True, null=True)),
                ('email', models.CharField(blank=True, max_length=122, null=True)),
                ('date', models.DateField()),
                ('tlog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.tlogs')),
            ],
        ),
    ]
