# Generated by Django 3.2.16 on 2022-12-20 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_tlog_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tlog_comment',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
