# Generated by Django 3.2.16 on 2022-12-20 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0022_login_dp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tlogs',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
