# Generated by Django 3.2.16 on 2022-12-20 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0023_alter_tlogs_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='login',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
